{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "ratify.labels" . | nindent 4 }}
  {{- if .Values.azureWorkloadIdentity.clientId }}
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: {{ .Values.azureWorkloadIdentity.clientId }}
  {{- end }}
  name: {{ include "ratify.serviceAccountName" . }}
{{- end }}
